# Generated by Django 5.2.5 on 2026-08-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
