# Generated by Django 5.2.5 on 2026-09-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatsession_chatmessage_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health'), ('wellness', 'Wellness'), ('therapy', 'Therapy'), ('tips', 'Tips & Advice'), ('success_stories', 'Success Stories'), ('other', 'Other')], default='other', max_length=50)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(help_text='Short summary of the blog post', max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
