import io
p = 'core/templates/core/blog_list.html'
lines = [
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'<meta charset="UTF-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
'<title>Blog — MyTherapyDoctor</title>',
'{% load static %}',
'<link rel="preconnect" href="https://fonts.googleapis.com">',
'<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
'<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0">',
'<link rel="alternate" type="application/rss+xml" title="MyTherapyDoctor Blog" href="https://mytherapydoctor.com{% url \'blog_feed\' %}">',
'<meta name="description" content="Mental health insights, wellness tips, therapy advice and success stories from the MyTherapyDoctor journal.">',
'<meta name="robots" content="index, follow, max-image-preview:large">',
'<link rel="canonical" href="https://mytherapydoctor.com/blog/">',
'<link rel="icon" type="image/png" href="{% static \'core/logo.png\' %}">',
'<meta property="og:type" content="website"><meta property="og:site_name" content="MyTherapyDoctor">',
'<meta property="og:title" content="Blog — MyTherapyDoctor">',
'<meta property="og:description" content="Mental health insights, wellness tips, and stories to support your journey.">',
'<meta property="og:url" content="https://mytherapydoctor.com/blog/">',
'<meta property="og:image" content="https://mytherapydoctor.com{% static \'core/Social.jpg\' %}">',
'<meta name="twitter:card" content="summary_large_image">',
'<meta name="twitter:title" content="Blog — MyTherapyDoctor">',
'<meta name="twitter:description" content="Mental health insights, wellness tips, and stories to support your journey.">',
'<style>',
'@import url("https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap");',
'@font-face{font-family:\'Playfair Display\';src:url("{% static \'PlayfairDisplay-SemiBoldItalic.ttf\' %}") format("truetype");font-weight:600;font-style:italic;font-display:swap}',
'.mat-icon{font-family:\'Material Symbols Outlined\';font-weight:normal;font-style:normal;line-height:1;letter-spacing:normal;text-transform:none;display:inline-block;white-space:nowrap;direction:ltr;font-size:18px;vertical-align:-3px}',
'*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}',
':root{--teal:#2e7d6e;--teal-light:#3d9e8c;--glass-bg:rgba(6,14,12,0.62);--glass-border:rgba(255,255,255,0.09);--text:#f0f4f3;--muted:rgba(240,244,243,0.55)}',
'html,body{width:100%;font-family:\'Inter\',sans-serif}',
'body{min-height:100vh;color:var(--text);overflow-x:hidden;background:linear-gradient(160deg,rgba(0,0,0,0.72)0%,rgba(0,18,14,0.55)100%),url("{% static \'core/section.jpg.jpeg\' %}") no-repeat center center/cover fixed}',
'#page{opacity:0;transition:opacity .6s ease,transform .7s ease}',
'#page.page-loaded{opacity:1;transform:none}',
'#page.page-exit{opacity:0;transform:scale(.97)}',
'</style>',
'</head>',
'<body>',
'<div id="page">',
'<p>PLACEHOLDER</p>',
'</div>',
'</body>',
'</html>',
]
io.open(p, 'w', encoding='utf-8').write(chr(10).join(lines))
print('done', len(lines), 'lines')
